# Generated by Django 5.1.4 on 2025-01-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
